# Generated by Django 5.2.1 on 2025-06-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Количество изделий в проектной спецификации', verbose_name='Количество')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_projects', to='catalog.catalogitem', verbose_name='Изделие из справочника')),
                ('project_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='units.projectunit', verbose_name='Комплектная единица проекта')),
            ],
            options={
                'verbose_name': 'Проектное изделие',
                'verbose_name_plural': 'Проектные изделия',
                'ordering': ['id'],
            },
        ),
    ]
