# Generated by Django 5.2.1 on 2025-06-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название проекта', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания проекта')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший проект', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectKTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_kts', models.ForeignKey(help_text='КТС из справочника', on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogkts')),
                ('project', models.ForeignKey(help_text='Проект, к которому привязан КТС', on_delete=django.db.models.deletion.CASCADE, related_name='project_kts', to='projects.project')),
            ],
            options={
                'verbose_name': 'КТС проекта',
                'verbose_name_plural': 'КТС проектов',
            },
        ),
    ]
