# Generated by Django 5.2.1 on 2025-06-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogkts_options_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectkts',
            options={'verbose_name': 'КТС в проекте', 'verbose_name_plural': 'КТС в проекте'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectkts',
            name='catalog_kts',
        ),
        migrations.AddField(
            model_name='projectkts',
            name='kts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogkts', verbose_name='КТС'),
        ),
        migrations.AddField(
            model_name='projectkts',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество КТС'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='projectkts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kts', to='projects.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество изделий')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem', verbose_name='Изделие')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изделие в проекте',
                'verbose_name_plural': 'Изделия в проекте',
            },
        ),
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество юнитов')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project', verbose_name='Проект')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogunit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Юнит в проекте',
                'verbose_name_plural': 'Юниты в проекте',
            },
        ),
    ]
