version: '3.8'

services:
  db:
    image: postgres:14
    container_name: specs_postgres
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped