# Generated by Django 5.2.1 on 2025-06-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('kts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество единиц')),
                ('catalog_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_units', to='catalog.catalogunit', verbose_name='Справочник комплектных единиц')),
                ('project_kts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='kts.projectkts', verbose_name='КТС проекта')),
            ],
            options={
                'verbose_name': 'Комплектная единица проекта',
                'verbose_name_plural': 'Комплектные единицы проекта',
            },
        ),
    ]
