import type { SpecNode } from "../types/types";

export const treeData: SpecNode[] = [
    {
        id: 1,
        key: 'project-1',
        title: 'Проект: Автоматизация склада',
        type: 'project',
        children: [
            {
                id: 11,
                key: 'ktc-11',
                title: 'КТС: Серверная часть',
                type: 'ktc',
                children: [
                    {
                        id: 111,
                        key: 'unit-111',
                        title: 'Комплектная единица: Сервер 1С',
                        type: 'unit',
                        children: [
                            {
                                id: 1111,
                                key: 'item-1111',
                                title: 'Сервер Dell PowerEdge R650',
                                type: 'item',
                                supplierName: 'ООО ТехноПоставка',
                                catalogCode: 'DELL-R650',
                                productName: 'Dell PowerEdge R650',
                                quantity: 1,
                                price: 5500,
                                manufacturer: 'Dell',
                                currency: 'USD',
                                deliveryType: 'DDP',
                            },
                            {
                                id: 1112,
                                key: 'item-1112',
                                title: 'Лицензия Windows Server 2022',
                                type: 'item',
                                supplierName: 'ООО СофтМаркет',
                                catalogCode: 'WIN-SRV-2022',
                                productName: 'Windows Server 2022 Standard',
                                quantity: 1,
                                price: 900,
                                manufacturer: 'Microsoft',
                                currency: 'USD',
                                deliveryType: 'DDP',
                            },
                        ],
                    },
                ],
            },
            {
                id: 12,
                key: 'ktc-12',
                title: 'КТС: Рабочие места',
                type: 'ktc',
                children: [
                    {
                        id: 121,
                        key: 'unit-121',
                        title: 'Комплектная единица: АРМ кладовщика',
                        type: 'unit',
                        children: [
                            {
                                id: 1211,
                                key: 'item-1211',
                                title: 'Моноблок Lenovo M70a',
                                type: 'item',
                                supplierName: 'ООО ПКПоставка',
                                catalogCode: 'LEN-M70A',
                                productName: 'Lenovo M70a',
                                quantity: 2,
                                price: 700,
                                manufacturer: 'Lenovo',
                                currency: 'RUB',
                                deliveryType: 'DDP',
                            },
                            {
                                id: 1212,
                                key: 'item-1212',
                                title: 'Принтер этикеток Zebra ZD420',
                                type: 'item',
                                supplierName: 'ООО ПринтЛайн',
                                catalogCode: 'ZEB-ZD420',
                                productName: 'Zebra ZD420',
                                quantity: 1,
                                price: 400,
                                manufacturer: 'Zebra',
                                currency: 'USD',
                                deliveryType: 'FCA',
                            },
                        ],
                    },
                ],
            },
        ],
    },
]