# Generated by Django 5.2.1 on 2025-06-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_kts', models.ForeignKey(help_text='Справочник КТС', on_delete=django.db.models.deletion.PROTECT, related_name='project_kts', to='catalog.catalogkts')),
                ('project', models.ForeignKey(help_text='Проект, к которому принадлежит этот КТС', on_delete=django.db.models.deletion.CASCADE, related_name='kts', to='projects.project')),
            ],
            options={
                'verbose_name': 'КТС проекта',
                'verbose_name_plural': 'КТС проектов',
            },
        ),
    ]
