# Generated by Django 5.2.1 on 2025-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('description', models.TextField(blank=True, verbose_name='Описание изделия')),
                ('supplier', models.CharField(max_length=255, verbose_name='Поставщик')),
                ('catalog_code', models.CharField(max_length=255, verbose_name='Каталожный код')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('manufactured', models.CharField(max_length=255, verbose_name='Производитель')),
                ('delivery_type', models.CharField(max_length=255, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogKTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название КТС')),
                ('description', models.TextField(blank=True, verbose_name='Описание КТС')),
            ],
            options={
                'verbose_name': 'Комплекс технических средств (КТС)',
                'verbose_name_plural': 'Комплексы технических средств (КТС)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название юнита')),
                ('description', models.TextField(blank=True, verbose_name='Описание юнита')),
            ],
            options={
                'verbose_name': 'Комплектная единица',
                'verbose_name_plural': 'Комплектные единицы',
                'ordering': ['name'],
            },
        ),
    ]
