# Generated by Django 5.2.1 on 2025-06-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='catalogkts',
            options={'verbose_name': 'Комплекс технических средств (КТС)', 'verbose_name_plural': 'Комплексы технических средств (КТС)'},
        ),
        migrations.AlterModelOptions(
            name='catalogunit',
            options={'verbose_name': 'Комплектная единица (Юнит)', 'verbose_name_plural': 'Комплектные единицы (Юниты)'},
        ),
        migrations.CreateModel(
            name='CatalogKTSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество изделий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem', verbose_name='Изделие')),
                ('kts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.catalogkts', verbose_name='КТС')),
            ],
            options={
                'verbose_name': 'Изделие в КТС',
                'verbose_name_plural': 'Изделия в КТС',
            },
        ),
        migrations.CreateModel(
            name='CatalogKTSUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество юнитов')),
                ('kts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.catalogkts', verbose_name='КТС')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogunit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Юнит в КТС',
                'verbose_name_plural': 'Юниты в КТС',
            },
        ),
        migrations.CreateModel(
            name='CatalogUnitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество изделий')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem', verbose_name='Изделие')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.catalogunit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Изделие в юните',
                'verbose_name_plural': 'Изделия в юните',
            },
        ),
    ]
