# Generated by Django 5.2.1 on 2025-06-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalogitem_options_alter_catalogkts_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalogunititem',
            constraint=models.UniqueConstraint(fields=('unit', 'item'), name='unique_unit_item'),
        ),
    ]
