# Generated by Django 5.2.1 on 2025-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogunititem_unique_unit_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalogktsitem',
            constraint=models.UniqueConstraint(fields=('kts', 'item'), name='unique_kts_item'),
        ),
        migrations.AddConstraint(
            model_name='catalogktsunit',
            constraint=models.UniqueConstraint(fields=('kts', 'unit'), name='unique_kts_unit'),
        ),
    ]
